# Generated by Django 2.0.2 on 2018-10-03 14:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=25)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(blank=True, default='', max_length=55, null=True)),
            ],
            options={
                'verbose_name': 'feature',
                'verbose_name_plural': 'features',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_photo', models.ImageField(default='images/properties/property.jpg', upload_to='images/properties/%Y/%m/%d')),
                ('sub_photo_1', models.ImageField(blank=True, default='images/properties/property.jpg', upload_to='images/properties/%Y/%m/%d')),
                ('sub_photo_2', models.ImageField(blank=True, default='images/properties/property.jpg', upload_to='images/properties/%Y/%m/%d')),
                ('sub_photo_3', models.ImageField(blank=True, default='images/properties/property.jpg', upload_to='images/properties/%Y/%m/%d')),
                ('sub_photo_4', models.ImageField(blank=True, default='images/properties/property.jpg', upload_to='images/properties/%Y/%m/%d')),
                ('house_name', models.CharField(blank=True, default='', max_length=55, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('owner', models.CharField(blank=True, default='', max_length=55, null=True)),
                ('phone', models.CharField(blank=True, max_length=18, null=True)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('size', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('parking', models.CharField(blank=True, default='No', max_length=10, null=True)),
                ('bedrooms', models.IntegerField(blank=True, default=1, null=True)),
                ('bathrooms', models.IntegerField(blank=True, default=1, null=True)),
                ('balcony', models.IntegerField(blank=True, default=1, null=True)),
                ('year_built', models.IntegerField(blank=True, default=0, null=True)),
                ('available_from', models.DateTimeField(auto_now_add=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.Category')),
                ('features', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.Feature')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
    ]
