# Generated by Django 2.0.2 on 2018-10-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_floor_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='size',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
