# Generated by Django 2.0.2 on 2018-10-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_auto_20181011_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='features',
        ),
        migrations.AddField(
            model_name='property',
            name='generator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='lift',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='security',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='telephone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='parking',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
