# Generated by Django 2.0.2 on 2018-10-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_auto_20181011_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='created_by',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
