# Generated by Django 2.0.2 on 2018-10-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_property_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
