# Generated by Django 2.0.2 on 2018-10-21 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_property_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='rating',
        ),
    ]
